activeviam/atoti-ui-migration

.vscode/jest.launch.config.js, .vscode/launch.json, src/migrateTextEditor.test.ts, src/migrateTextEditor.ts
Adds handling of katex formula migration:
Old notation
```
$ inline formula $
$$ block formula $$
```
becomes
```
`katex inline formula`
```katex
block formula
\```
```
=> UI-6728 - Migrate katex formulas

src/migrateTextEditor.ts
The used regular expressions already used `g`, making `.replaceAll` directly convertible into `.replace`.
I checked that `migrateTextEditor.test.ts` still passes. It does. Too bad we do not have a CI here yet, which tells it unambiguously to the reviewer.
=> UI-6890 - Fix migration script failing on text editor widgets when run with nodeJS < v15

README.md
`npm run` does not run executables. In fact it's not even listed in the [`npm` CLI](https://docs.npmjs.com/cli/v7/commands).
[`npm exec`](https://docs.npmjs.com/cli/v7/commands/npm-exec) or [`npx`](https://docs.npmjs.com/cli/v7/commands/npx) should be used instead.
In our case, `npx` is more straightforward to avoid having to separate `npm exec` arguments from the actual executable arguments, (see the [docs](https://docs.npmjs.com/cli/v7/commands/npx#npx-vs-npm-exec)).
Alternatives: 
- document using `yarn` instead of `npm`.
- do not go through the trouble of [creating a directory, doing `npm init`, `npm install activeui-migration`, and then only `npx migrate`], and rather temporarily install `activeui-migration` globally and run the command in one go through `npx -p activeui-migration …
=> UI-6956 - Fix command in docs

src/cli/bin.ts
The problem is explained in the ticket description: [UI-7198](https://support.activeviam.com/jira/browse/UI-7198)
I haven't found a better solution than to call `process.exit` manually.
In particular, I have researched things like "yargs Node 16 process not exiting", and the polyfill warnings, and I did not find any related issue.
To test, having [this ](https://github.com/activeviam/activeui-migration/pull/4) merged would have been helpful, so I'm glad we're in the process of adding it.
In the meantime, you can use [`npm link`](https://docs.npmjs.com/cli/v8/commands/npm-link):
```bash
// Starting from activeui-migration:
git co personal/a.tissier/UI-7198-fix-cli-with-node-16
git pull
yarn && yarn build
npm link
cd ..
mkdir migration_test
npm init
npm link activeui-migration
npx migrate …
```
=> UI-7198 - Fix running the CLI with Node 16

README.md, src/__snapshots__/migrateUIFolder.test.ts.snap, src/__test_resources__/legacyDashboard.ts, src/__test_resources__/legacyPageFilters.ts, src/__test_resources__/legacyUIFolder.ts, src/_getLegacyWidgetPluginKey.ts, src/cli/bin.ts, src/migrateDashboard.test.ts, src/migrateDashboard.ts, src/migrateUIFolder.test.ts, src/migrateUIFolder.ts, src/migrateWidget.test.ts, src/migrateWidget.ts
The rationale is explained in [UI-7229](https://support.activeviam.com/jira/browse/UI-7229), which comes from a client request at CIBC: [NAS-3463](https://support.activeviam.com/jira/browse/NAS-3463
)
You can review commit by commit.
=> UI-7229 - Option to remove widgets of a given type in the CLI

.github/workflows/auto-update.yml, .github/workflows/jira-check.yml
Current version is deprecated and will cease to work on december 1st.
=> UI-7687 - Bump ubuntu executor version

package.json, yarn.lock
Part of [UI-7834,](https://support.activeviam.com/jira/browse/UI-7834) Migrate calculated measures from the content server to the AP cube. 
Bump the version of the SDK in `package.json` in order to use the function `removeCalculatedMemberDefinition`, which was exported in [PR #2957](https://github.com/activeviam/activeui/pull/2957).
=> UI-7834 - Add 5.1 SDK dependency

src/4.3_to_5.0/migrate_43_to_50.test.ts, src/4.3_to_5.0/migrate_43_to_50.ts, src/cli/bin.ts
At the moment, `migrate_43_to_50` accepts `legacyUIFolder` as an argument, and returns the newly `migratedUIFolder`.
It also takes `legacyPivotFolder` as an argument.
It also creates and returns the `counters` and the `errorReport`.
For migration functions to be generically composable, a simpler design would be to have it:
* take the whole content server as an argument: no need for `legacyUIFolder` and `legacyPivotFolder` anymore
* mute the content server object inside the function
* accept `counters` and `errorReport` as arguments and mutate them inside
* return a `Promise<void>`
=> UI-8014 - migrate_43_to_50 only accepts and mutates contentServer, counters and errorReport

src/5.0_to_5.1/calculated-measures/migrateCalculatedMeasures.test.ts, src/5.0_to_5.1/calculated-measures/migrateCalculatedMeasures.ts
Jira ticket : [UI-7834](https://support.activeviam.com/jira/browse/UI-7834)
In PR #57, certain files were changed to use the indexed version of the `DataModel` from 5.1. I hadn't merged the changes from that PR into #59 before merging, which has lead to type errors and failing unit tests. This PR fixes these problems.
=> UI-7834 - Quick fix for `migrateCalculatedMeasures`

src/5.0_to_5.1/calculated-measures/migrateCalculatedMeasures.test.ts, src/5.0_to_5.1/calculated-measures/migrateCalculatedMeasures.ts, src/5.0_to_5.1/calculated-measures/migrateCalculatedMeasuresInDashboards.test.ts, src/5.0_to_5.1/calculated-measures/migrateCalculatedMeasuresInDashboards.ts, src/5.0_to_5.1/calculated-measures/migrateCalculatedMeasuresInMdx.test.ts, src/5.0_to_5.1/calculated-measures/migrateCalculatedMeasuresInMdx.ts, src/5.0_to_5.1/calculated-measures/migrateCalculatedMeasuresInWidgets.test.ts, src/5.0_to_5.1/calculated-measures/migrateCalculatedMeasuresInWidgets.ts
Aligning on the other migration functions to use `dataModels` instead of `dataModel`.
Indeed, there can be several target ActivePivot servers.
=> UI-7645 - Support several servers when migrating calculated measures

src/5.0_to_5.1/migrateDashboard.ts, src/5.0_to_5.1/migrateWidget.ts, src/5.0_to_5.1/migrate_5.0_to_5.1.ts, src/migration.types.ts
Adding an extra `Options` generic for the migration callbacks, representing the extra options that one specific migration function might have.
For example `namesOfCalculatedMeasuresToMigrate` is necessary for the dashboard/widget migration callback of 5.0 to 5.1, but it most likely won't be for 5.1 to 5.2.
Doing it this way allows to assign `MigrateXyzCallback` to some variables while still keep the factorization for the other common args (e.g. `dataModels`)
=> UI-7645 - Refactor types for extra migration callback args

src/4.3_to_5.0/migrate_43_to_50.ts, src/_addCorruptFileErrorToReport.ts, src/cli/bin.ts, src/getMigrateDashboards.ts, src/getMigrateSavedFilters.ts, src/getMigrateSavedWidgets.ts
We were properly handling corrupt content (= saved content for which there is a file in `content` but no matching file(s) in `structure`) for the migration from 4.3 to 5.0, but not for the new migration functions.
This PR adds this handling.
=> UI-7645 - Handle corrupt content

src/5.0_to_5.1/createFilterWithFirstMatchingCube.ts, src/5.0_to_5.1/createFilterWithFirstMatchingDataModel.ts, src/5.0_to_5.1/getAllCubes.ts, src/5.0_to_5.1/migrateDashboard.ts, src/5.0_to_5.1/migrateFilters.test.ts, src/5.0_to_5.1/migrateFilters.ts, src/5.0_to_5.1/migrateSavedFilter.test.ts, src/5.0_to_5.1/migrateSavedFilter.ts, src/5.0_to_5.1/migrateWidget.ts, src/5.0_to_5.1/migrate_5.0_to_5.1.ts
Migrates filters from `MdxExpression` in 5.0 to `Filter` in 5.1.
Saved filters had an extra wrapper: `{mdx: MdxExpression}`, but in 5.1 saved filters and filters within widgets/dashboards are exactly the same.
=> UI-7645 - Filters migration

src/getMigrateDashboards.ts
The `widgets.removed` counter is not incremented when the key of a widget within a dashboard is specified in the `--remove-widgets`. This PR fixes that.
=> UI-8182 - Increment widgets.removed counter when widget key in keysOfWidgetPluginsToRemove

src/getMigrateSavedFilters.ts, src/getMigrateSavedWidgets.ts
`counters.dashboards.removed` was incremented instead of `counters.widgets.removed` and `counters.filters.removed`. This PR fixes that.
=> UI-8181 - Fix wrong counter being incremented

src/4.3_to_5.0/__test_resources__/legacyPivotTableWithCrossjoinOnColumnsAndHiddenColumns.ts, src/4.3_to_5.0/__test_resources__/legacyPivotTableWithHiddenColumns.ts, src/4.3_to_5.0/__test_resources__/legacyTableWithHiddenColumns.ts, src/4.3_to_5.0/_getHiddenColumnKeys.test.ts, src/4.3_to_5.0/_getHiddenColumnKeys.ts, src/4.3_to_5.0/migrateTable.test.ts, src/4.3_to_5.0/migrateTable.ts
Before this PR, hidden columns in AUI 4.3 would not be hidden post-migration, when the table is viewed in AUI 5.0.
This PR fixes it.
=> UI-8532 - Take hidden columns into account during table migrations from 4.3 to 5.0

src/4.3_to_5.0/_migrateTableColumnWidths.ts, src/4.3_to_5.0/getTreeColumnKey.ts
This error is thrown when the user passes the option `--tree-column-width` but some of their widgets don' have any field on rows.
This PR fixes it.
=> UI-8812 - Fix 'Cannot read properties of undefined (reading 'type')' error when passing the --tree-column-width option

src/4.3_to_5.0/migrateDashboard.test.ts, src/4.3_to_5.0/migrateDashboard.ts
This is a blocker for the Santander upgrade (from 4.3 to 5.1).
The error is not mentioned in the ticket, but the scenario is well enough described that I could reproduce it with a unit test.
The cause is that during the 4.3 -> 5.0 migration, we would not add anything under `page.content` for widgets that would be removed anyway. The problem is that the widget removal logic depends on it being present both in layout and [in content](https://github.com/activeviam/atoti-ui/blob/6d19eadb48bd756280c0208f078ed8805ad873b4/packages/dashboard-base/src/utils/removeWidget.ts#L67).
This PR fixes the bug and should unlock the Santander upgrade.
=> UI-8859 - Fix error thrown when all widgets but one are removed from a page

src/4.3_to_5.0/__snapshots__/getCalculatedMeasures.test.ts.snap, src/4.3_to_5.0/getCalculatedMeasures.test.ts, src/4.3_to_5.0/getCalculatedMeasures.ts
See UI-8803, and the added test: the problem is that the `calculatedMember` tag in the customer's XML is prefixed with a namespace (`ns2`).
Adding a [tag processor](https://www.npmjs.com/package/xml2js#processing-attribute-tag-names-and-values) allows to remove it from the parsed JSON.
Note that when migrating all the way from 4.3 to 5.1, then:
- during 4.3 to 5.0, the prefix is removed
- it it not added again in 5.0 to 5.1
I honestly think it's fine, and would prefer for clients to report an issue before trying to preserve it.
For example, in this example from the customer, [`ns2` is actually a dummy namespace that should only be used in test cases](https://www.w3.org/XML/2008/xsdl-exx/ns2).
=> UI-8803 - Support namespaces in XML calculated members

README.md, package.json
Half our README snippets don't work, causing SocGen and Santander to not manage to use our migration script without help from ActiveViam CS.
This PR fixes it.
=> UI-9025 - Fix command snippets in README.md

src/4.3_to_5.0/__test_resources__/legacyComparisonValues.ts, src/4.3_to_5.0/__test_resources__/legacyKpi.ts, src/4.3_to_5.0/getMigratedKpiTitles.test.ts, src/4.3_to_5.0/getMigratedKpiTitles.ts, src/4.3_to_5.0/migrateKpi.test.ts, src/4.3_to_5.0/migrateKpi.ts, src/PartialMigrationError.ts
This ensures that KPI titles manually entered by users on Atoti UI 4.3 are still honored when they open their dashboards after a 4.3 -> 5.0 content migration.
The changes might seem bigger than expected. It is because both Atoti UI 4.3 and 5.0 use the unique names of its members in order to identify a tuple, but they don't do it in the same order unfortunately.
Atoti UI 5.0 does:
- fields on columns (including measures if present)
- fields on rows (including measures if present)
Atoti UI 4.3 does:
- fields on rows (including measures if present)
- fields on columns (including measures if present)
=> UI-9384 - Preserve KPI titles when migrated KPI widgets from 4.3 to 5.0
