.circleci/config.yml

Setup the workflow to build, check the linting, and run the tests after each commit on a non-protected branch.
The idea is to prevent to keep `main` always green by preventing to merge non-protected branches into it unless this workflow was successful.
Once this is merged, CircleCI will have to be setup for this repo.

UI-6206 - Add config.yml to check pull requests

---

package.json
src/__snapshots__/migrateUIFolder.test.ts.snap
src/migrateSettingsFolder.ts
src/migrateUIFolder.ts

Depending on `@activeviam/content-server-initialization` to make sure the migration scripts stay in sync with the latest additions in ActiveUI.

UI-7142 - Use factorized content server initialization utils

---

webpack.config.js

I was not able to run `yarn build` unless I add this.

UI-7416 - add webpack loader for woff font files

---

package.json
yarn.lock

Bumping the package version as well as the @activeviam dependencies.

Release 5.0.8

---

package.json

5.0.9 is the next stable release.

Bump version to 5.0.9-SNAPSHOT

---

package.json
src/migrateUIFolder.ts
yarn.lock

Adds a progress bar for creature confort:

UI-7486 - Add progress bar on main loop

---

package.json

UI-6616 - Release 5.0.9

---

src/5.0_to_5.1/migrate_5.0_to_5.1.ts
src/cli/bin.ts
src/getMigrateSavedFilters.ts
src/getMigrateSavedWidgets.ts
src/migration.types.ts

Some renaming to avoid any ambiguity.

UI-8070 - Differentiate saved filters/widgets from filters/widgets within a dashboard

---

src/5.0_to_5.1/migrateWidget.ts

UI-7065
https://github.com/activeviam/activeui/pull/3243

UI-7065 - Migrate widget plugin key of combo charts

---

src/getMigrateDashboards.ts
src/getMigrateSavedFilters.ts
src/getMigrateSavedWidgets.ts

A corrupted file is a file which content is saved, but is not present in the structure. At the moment, during the migration we spot them, account for them in the error report and counters, but we don't actually remove them.

UI-8188 - Remove corrupt files from content server

---

src/5.0_to_5.1/__test_resources__/contentServer.ts
src/5.0_to_5.1/migrateSavedWidgetsMetaData.ts
src/5.0_to_5.1/migrate_5.0_to_5.1.ts
src/_getMetaData.ts
src/migrateSavedWidgetsMetaData.test.ts

UI-8176 - Make property `version` of `WidgetMetaData` mandatory

---

src/5.0_to_5.1/__test_resources__/contentServer.ts
src/5.0_to_5.1/migrateUserActivity.test.ts
src/5.0_to_5.1/migrateUserActivity.ts

Without these safeguards, an error would be thrown if the user activity has no user filters.

UI-6616 - Safely migrate user activity

---

package.json

UI-6616 - Release 5.1.0

---

package.json

UI-6616 - Prepare 5.1.1

---

.circleci/config.yml

UI-8253 - Change email address to clients.rnd@activeviam.com

---

.circleci/config.yml
README.md

See https://github.com/activeviam/activeui/pull/3436 and https://github.com/activeviam/activeui/pull/3440

UI-8317 - Fix artifactory auth

---

README.md

Jira ticket: [UI-8353](https://activeviam.atlassian.net/browse/UI-8358)
The repository has been renamed to `atoti-ui-migration`. This updates the README file to use the new termminology.

UI-8358 - Update README.md

---

README.md

Part of UI-8299.
Update of the README

UI-8299 - Support notebooks in the Content Migration Tool - update README

---

README.md

UI-8722 -   Update broken documentation links in AUI migration

---

package.json

UI-6616 - Release atoti-ui-migration 5.1.1

---

package.json

UI-6616 - Prepare 5.1.2
